ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --timeout=30
  inifile: C:\code\DazzleTreeLib\pyproject.toml
  rootdir: C:\code\DazzleTreeLib

